package romanow.abc.android;

import firefighter.core.reports.R01_TechnicianReport;

public enum ReportType {
    TECHNICIANREPORT, PAYMENTREPORT, SERVICECOMPANYREPORT,
    FACILITYREPORT, PAYMENT1REPORT, PAYMENT2REPORT,
    PAYMENT3REPORT, PAYMENT4REPORT, DEPT1REPORT,
    DEPT2REPORT, DEPT3REPORT, DEPT4REPORT,
    DEPT5REPORT, CONTRACTORREPORT, TECHNICIANPLANREPORT
}
